server.port : 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: covid
    url: ${USER-DATASOURCE:jdbc:postgresql://postgresql:5432/userdb}
    username: covid
  jpa:
    hibernate:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
      generate-ddl: true
      open-in-view: false
      show-sql: true
